[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_PROD"
schema = "bronze"
account = "SOLITA-SOLITA_TRAINING"
user = "MIKKO.MATTILA@SOLITA.FI"
authenticator = "externalbrowser"
# password = "<INSERT YOUR PASSWORD>"
